/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Documents */
        get: operations["documents_api_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/load-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Issues */
        get: operations["load_issues_api_load_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Questions */
        get: operations["questions_api_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/bump-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bump Version */
        post: operations["bump_version_api_documents__document_id__bump_version_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Question */
        get: operations["question_api_questions__question_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Draft */
        put: operations["edit_draft_api_questions__question_id__draft_put"];
        /** Draft */
        post: operations["draft_api_questions__question_id__draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_questions__question_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}/leave-open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leave Open */
        post: operations["leave_open_api_questions__question_id__leave_open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questionnaire/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run All */
        post: operations["run_all_api_questionnaire_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Approval */
        Approval: {
            /** Approver */
            approver: string;
            /** Approved At */
            approved_at: string;
            /** Source Versions */
            source_versions: {
                [key: string]: number;
            };
        };
        /** ApproveRequest */
        ApproveRequest: {
            /** Approver */
            approver: string;
        };
        /** BumpResult */
        BumpResult: {
            /** Id */
            id: string;
            /** Version */
            version: number;
        };
        /**
         * CallInfo
         * @description The model call that made the draft. `when` is its `created_at`.
         */
        CallInfo: {
            /**
             * Label
             * @enum {string}
             */
            label: "real" | "cached" | "simulated";
            /** Model */
            model: string;
            /** When */
            when: string;
        };
        /**
         * DocumentView
         * @description A document for the Sources tab. `replaced_by` is computed; the `status` label is not shown.
         */
        DocumentView: {
            /** Id */
            id: string;
            /** Version */
            version: number;
            /** Date */
            date: string;
            /** Supersedes Id */
            supersedes_id: string | null;
            /** Replaced By */
            replaced_by: string | null;
            /** Passages */
            passages: components["schemas"]["PassageView"][];
        };
        /** EditRequest */
        EditRequest: {
            /** Answer */
            answer: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaveOpenRequest */
        LeaveOpenRequest: {
            /** Note */
            note: string;
        };
        /** LoadIssue */
        LoadIssue: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "duplicate_id" | "missing_document" | "missing_superseded" | "missing_owner";
            /** Id */
            id: string;
            /** Message */
            message: string;
        };
        /** PassageView */
        PassageView: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** QuestionSummary */
        QuestionSummary: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /** Text */
            text: string;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "draft" | "unresolved" | "approved" | "needs_review" | "error";
            /** Owner */
            owner: string | null;
            /** Warning Count */
            warning_count: number;
        };
        /** QuestionView */
        QuestionView: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /** Text */
            text: string;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "draft" | "unresolved" | "approved" | "needs_review" | "error";
            /** Answer */
            answer: string | null;
            /** Citations */
            citations: components["schemas"]["ViewCitation"][];
            /** Warnings */
            warnings: components["schemas"]["Warning"][];
            /** Owner */
            owner: string | null;
            /** Replaced */
            replaced: components["schemas"]["ReplacedEvidence"][];
            /** Label */
            label: ("real" | "cached" | "simulated") | null;
            call: components["schemas"]["CallInfo"] | null;
            /** Error */
            error: string | null;
            /** Edited */
            edited: boolean;
            /** Note */
            note: string | null;
            approved?: components["schemas"]["Approval"] | null;
            /** Allowed Actions */
            allowed_actions: ("generate" | "retry" | "edit" | "approve" | "leave_open" | "ask_again")[];
        };
        /**
         * ReplacedEvidence
         * @description A passage of a document that a cited document replaces. Shown, never sent to the model.
         */
        ReplacedEvidence: {
            /** Passage Id */
            passage_id: string;
            /** Excerpt */
            excerpt: string;
            /** Replaced By */
            replaced_by: string;
            /** Version */
            version: number;
            /** Date */
            date: string;
        };
        /** RunAllResult */
        RunAllResult: {
            /** Asked */
            asked: string[];
        };
        /** SummaryCounts */
        SummaryCounts: {
            /** New */
            new: number;
            /** Draft */
            draft: number;
            /** Unresolved */
            unresolved: number;
            /** Approved */
            approved: number;
            /** Needs Review */
            needs_review: number;
            /** Error */
            error: number;
            /** Answered */
            answered: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ViewCitation
         * @description A citation as the view shows it. `version` is the cited document's version in the approved
         *     snapshot, or its version now while the answer is a draft. `current_version` is that document's
         *     version now; None while the answer is not approved.
         */
        ViewCitation: {
            /** Passage Id */
            passage_id: string;
            /** Excerpt */
            excerpt: string;
            /** Version */
            version?: number | null;
            /** Current Version */
            current_version?: number | null;
            /** Date */
            date?: string | null;
            /**
             * Source Changed
             * @default false
             */
            source_changed: boolean;
        };
        /** Warning */
        Warning: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "citation_not_found" | "no_citation" | "superseded" | "source_changed" | "support_check" | "support_check_failed";
            /** Passage Id */
            passage_id?: string | null;
            /** Message */
            message: string;
            /** Document Id */
            document_id?: string | null;
            /** Old Version */
            old_version?: number | null;
            /** New Version */
            new_version?: number | null;
            /** Supersedes Id */
            supersedes_id?: string | null;
            /** Older Text */
            older_text?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    documents_api_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"][];
                };
            };
        };
    };
    load_issues_api_load_issues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadIssue"][];
                };
            };
        };
    };
    questions_api_questions_get: {
        parameters: {
            query?: {
                status?: ("new" | "draft" | "unresolved" | "approved" | "needs_review" | "error") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bump_version_api_documents__document_id__bump_version_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BumpResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryCounts"];
                };
            };
        };
    };
    question_api_questions__question_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_draft_api_questions__question_id__draft_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_api_questions__question_id__draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_questions__question_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_open_api_questions__question_id__leave_open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveOpenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_all_api_questionnaire_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAllResult"];
                };
            };
        };
    };
}
