/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/load-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Issues */
        get: operations["load_issues_api_load_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Questions */
        get: operations["questions_api_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Question */
        get: operations["question_api_questions__question_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft */
        post: operations["draft_api_questions__question_id__draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Citation */
        Citation: {
            /** Passage Id */
            passage_id: string;
            /** Excerpt */
            excerpt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoadIssue */
        LoadIssue: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "duplicate_id" | "missing_document" | "missing_superseded" | "missing_owner";
            /** Id */
            id: string;
            /** Message */
            message: string;
        };
        /** QuestionSummary */
        QuestionSummary: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /** Text */
            text: string;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "draft" | "unresolved" | "error";
        };
        /** QuestionView */
        QuestionView: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /** Text */
            text: string;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "draft" | "unresolved" | "error";
            /** Answer */
            answer: string | null;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Warnings */
            warnings: components["schemas"]["Warning"][];
            /** Owner */
            owner: string | null;
            /** Replaced */
            replaced: components["schemas"]["ReplacedEvidence"][];
            /** Error */
            error: string | null;
            /** Allowed Actions */
            allowed_actions: ("generate" | "retry")[];
        };
        /**
         * ReplacedEvidence
         * @description A passage of a document that a cited document replaces. Shown, never sent to the model.
         */
        ReplacedEvidence: {
            /** Passage Id */
            passage_id: string;
            /** Excerpt */
            excerpt: string;
            /** Replaced By */
            replaced_by: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Warning */
        Warning: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "citation_not_found" | "no_citation" | "superseded";
            /** Passage Id */
            passage_id?: string | null;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    load_issues_api_load_issues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadIssue"][];
                };
            };
        };
    };
    questions_api_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSummary"][];
                };
            };
        };
    };
    question_api_questions__question_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_api_questions__question_id__draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
